import { ConversationChannel } from '../messages/messages.types';

export type Intent =
  | "START_CONVERSATION" // New intent for initial greetings
  | "COMPANY_INFORMATION"
  | "CHECK_AVAILABILITY"
  | "CREATE_APPOINTMENT"
  | "CANCEL_APPOINTMENT"
  | "RESCHEDULE_APPOINTMENT"
  | "CUSTOMER_INFORMATION"
  | "OWNER_COMMAND"
  | "HUMAN_HANDOFF"
  | "UNKNOWN"
  // Legacy mappings for unit tests backward compatibility
  | "BOOK_APPOINTMENT"
  | "GENERAL_INFORMATION";

export interface ExtractedEntities {
  service?: string;
  professional?: string;
  date?: string; // ISO 8601 format (YYYY-MM-DD)
  time?: string; // HH:MM format
  customerName?: string; // Full name or first/last
  customerPhone?: string; // Normalized phone number
}

export interface ExtractedIntent {
  intent: Intent;
  entities: ExtractedEntities;
  confidence: number; // 0.0 to 1.0
  language?: string; // Detected language, e.g., 'it', 'en', 'pt'
}

export interface ToolCallTelemetry {
  toolName: string;
  arguments: Record<string, unknown>;
  result: unknown;
  executionTimeMs: number;
}

export interface StructuredMessageOption {
  id: string;
  label: string;
  description?: string;
  payload?: Record<string, any>;
}

export interface StructuredMessageAction {
  id: string; // e.g. 'confirm' | 'modify'
  label: string; // e.g. 'Conferma' | 'Modifica'
  variant?: 'primary' | 'secondary';
}

export interface StructuredMessageField {
  id: string;
  label: string;
  type?: 'text' | 'tel' | 'email';
  placeholder?: string;
  required?: boolean;
}

export type StructuredMessageType =
  | 'TEXT'
  | 'OPTION_LIST'
  | 'SERVICE_SELECTION'
  | 'PROFESSIONAL_SELECTION'
  | 'DAY_SELECTION'
  | 'TIME_SELECTION'
  | 'SLOT_SELECTION'
  | 'IDENTITY_FORM'
  | 'CONFIRMATION_CARD'
  | 'SUMMARY';

export interface StructuredMessage {
  type: StructuredMessageType;
  content: string;
  options?: StructuredMessageOption[];
  /** Action buttons for confirmation-style cards (e.g. Conferma / Modifica). */
  actions?: StructuredMessageAction[];
  /** Input fields for form-style cards (e.g. identity: nome / cognome / telefono). */
  fields?: StructuredMessageField[];
  /** Extra data for the UI (e.g. booking summary details). */
  payload?: Record<string, any>;
}

/**
 * A card click coming from the WebChat UI. The server treats card selections
 * as explicit, deterministic user choices — never as AI decisions.
 */
export interface CardSelection {
  type: 'service' | 'professional' | 'date' | 'time' | 'slot' | 'confirm' | 'modify';
  id?: string;
  label?: string;
  payload?: Record<string, any>;
}

/**
 * Persisted multi-turn state for guided operational flows (e.g. booking).
 * Stored on the conversations table as workflow_state (jsonb).
 */
export interface ConversationWorkflowState {
  intent?: 'CREATE_APPOINTMENT' | 'RESCHEDULE_APPOINTMENT' | 'CHECK_AVAILABILITY';
  serviceId?: string;
  serviceName?: string;
  professionalId?: string | null;
  professionalName?: string | null;
  professionalPreference?: 'specific' | 'any' | null;
  date?: string | null;
  startDate?: string | null;
  endDate?: string | null;
  time?: string | null;
  customerId?: string | null;
  customerName?: string | null;
  appointmentId?: string | null;
  step?: 'SERVICE' | 'PROFESSIONAL' | 'SLOTS' | 'DATE' | 'TIME' | 'IDENTITY' | 'CONFIRMATION' | 'CREATE' | 'COMPLETED' | 'CANCELLED' | 'RESCHEDULING';
}

export type OperationalResultType =
  | 'BOOKING_CREATED'
  | 'SLOTS_AVAILABLE'
  | 'DATE_REQUIRED'
  | 'SERVICE_SELECTION_REQUIRED'
  | 'PROFESSIONAL_SELECTION_REQUIRED'
  | 'CONFIRMATION_REQUIRED'
  | 'UNKNOWN_INTENT'
  | 'COMPANY_INFORMATION_FOUND'
  | 'APPOINTMENT_CANCELLED'
  | 'APPOINTMENT_RESCHEDULED'
  | 'SLOT_OCCUPIED'
  | 'WELCOME'
  | 'NO_SERVICES_AVAILABLE'
  | 'NO_SLOTS_AVAILABLE'
  | 'APPOINTMENT_CREATION_FAILED'
  | 'CUSTOMER_FULL_NAME_REQUIRED'
  | 'CUSTOMER_IDENTITY_REQUIRED'
  | 'HUMAN_HANDOFF_REQUESTED';

export interface OperationalResult {
  type: OperationalResultType;
  data: Record<string, any>;
  language: string;
  criticalData: string[]; // Data points that MUST be present in the humanized response
  baseReplyText: string; // The original, safe reply text generated by DRG
}

export interface ConversationTurnResult {
  replyText: string;
  detectedIntent: Intent;
  toolCalls: ToolCallTelemetry[];
  conversationId: string;
  processingTimeMs: number;
  metadata?: Record<string, any>;
}
/**
 * Server-only provenance for messages sent from an authenticated organization
 * workspace. It is intentionally not part of any channel payload.
 */
export interface TrustedConversationContext {
  source: 'organization_workspace';
  /**
   * Test-only clock override (ISO 8601). When present, every time decision
   * in the turn (date resolution, availability window, min-advance, past-date
   * guard) is computed relative to this instant instead of the wall clock.
   */
  referenceTime?: string;
}
export interface ChannelAdapter {
  readonly channelName: ConversationChannel;
  receiveMessage(payload: unknown): Promise<{ conversationId?: string; customerPhone?: string; text: string; selection?: CardSelection }>;
  sendReply(destination: string, text: string): Promise<boolean>;
}
