/**
 * Complete list of international dialing codes with country names in Italian and flag emojis.
 * Sorted alphabetically by Italian country name, with Italy pinned first.
 */
export interface CountryDialCode {
  code: string;    // E.164 country code, e.g. "+39"
  name: string;    // Country name in Italian
  flag: string;    // Emoji flag
  iso: string;     // ISO 3166-1 alpha-2
}

export const COUNTRY_DIAL_CODES: CountryDialCode[] = [
  // Italy first (default)
  { code: '+39', name: 'Italia', flag: '🇮🇹', iso: 'IT' },
  // Alphabetical by Italian name
  { code: '+93', name: 'Afghanistan', flag: '🇦🇫', iso: 'AF' },
  { code: '+355', name: 'Albania', flag: '🇦🇱', iso: 'AL' },
  { code: '+213', name: 'Algeria', flag: '🇩🇿', iso: 'DZ' },
  { code: '+376', name: 'Andorra', flag: '🇦🇩', iso: 'AD' },
  { code: '+244', name: 'Angola', flag: '🇦🇴', iso: 'AO' },
  { code: '+1268', name: 'Antigua e Barbuda', flag: '🇦🇬', iso: 'AG' },
  { code: '+966', name: 'Arabia Saudita', flag: '🇸🇦', iso: 'SA' },
  { code: '+54', name: 'Argentina', flag: '🇦🇷', iso: 'AR' },
  { code: '+374', name: 'Armenia', flag: '🇦🇲', iso: 'AM' },
  { code: '+61', name: 'Australia', flag: '🇦🇺', iso: 'AU' },
  { code: '+43', name: 'Austria', flag: '🇦🇹', iso: 'AT' },
  { code: '+994', name: 'Azerbaigian', flag: '🇦🇿', iso: 'AZ' },
  { code: '+1242', name: 'Bahamas', flag: '🇧🇸', iso: 'BS' },
  { code: '+973', name: 'Bahrein', flag: '🇧🇭', iso: 'BH' },
  { code: '+880', name: 'Bangladesh', flag: '🇧🇩', iso: 'BD' },
  { code: '+1246', name: 'Barbados', flag: '🇧🇧', iso: 'BB' },
  { code: '+32', name: 'Belgio', flag: '🇧🇪', iso: 'BE' },
  { code: '+501', name: 'Belize', flag: '🇧🇿', iso: 'BZ' },
  { code: '+229', name: 'Benin', flag: '🇧🇯', iso: 'BJ' },
  { code: '+975', name: 'Bhutan', flag: '🇧🇹', iso: 'BT' },
  { code: '+375', name: 'Bielorussia', flag: '🇧🇾', iso: 'BY' },
  { code: '+95', name: 'Birmania (Myanmar)', flag: '🇲🇲', iso: 'MM' },
  { code: '+591', name: 'Bolivia', flag: '🇧🇴', iso: 'BO' },
  { code: '+387', name: 'Bosnia ed Erzegovina', flag: '🇧🇦', iso: 'BA' },
  { code: '+267', name: 'Botswana', flag: '🇧🇼', iso: 'BW' },
  { code: '+55', name: 'Brasile', flag: '🇧🇷', iso: 'BR' },
  { code: '+673', name: 'Brunei', flag: '🇧🇳', iso: 'BN' },
  { code: '+359', name: 'Bulgaria', flag: '🇧🇬', iso: 'BG' },
  { code: '+226', name: 'Burkina Faso', flag: '🇧🇫', iso: 'BF' },
  { code: '+257', name: 'Burundi', flag: '🇧🇮', iso: 'BI' },
  { code: '+855', name: 'Cambogia', flag: '🇰🇭', iso: 'KH' },
  { code: '+237', name: 'Camerun', flag: '🇨🇲', iso: 'CM' },
  { code: '+1', name: 'Canada', flag: '🇨🇦', iso: 'CA' },
  { code: '+238', name: 'Capo Verde', flag: '🇨🇻', iso: 'CV' },
  { code: '+235', name: 'Ciad', flag: '🇹🇩', iso: 'TD' },
  { code: '+56', name: 'Cile', flag: '🇨🇱', iso: 'CL' },
  { code: '+86', name: 'Cina', flag: '🇨🇳', iso: 'CN' },
  { code: '+357', name: 'Cipro', flag: '🇨🇾', iso: 'CY' },
  { code: '+57', name: 'Colombia', flag: '🇨🇴', iso: 'CO' },
  { code: '+269', name: 'Comore', flag: '🇰🇲', iso: 'KM' },
  { code: '+242', name: 'Congo', flag: '🇨🇬', iso: 'CG' },
  { code: '+243', name: 'Congo (RDC)', flag: '🇨🇩', iso: 'CD' },
  { code: '+850', name: 'Corea del Nord', flag: '🇰🇵', iso: 'KP' },
  { code: '+82', name: 'Corea del Sud', flag: '🇰🇷', iso: 'KR' },
  { code: '+225', name: "Costa d'Avorio", flag: '🇨🇮', iso: 'CI' },
  { code: '+506', name: 'Costa Rica', flag: '🇨🇷', iso: 'CR' },
  { code: '+385', name: 'Croazia', flag: '🇭🇷', iso: 'HR' },
  { code: '+53', name: 'Cuba', flag: '🇨🇺', iso: 'CU' },
  { code: '+45', name: 'Danimarca', flag: '🇩🇰', iso: 'DK' },
  { code: '+1767', name: 'Dominica', flag: '🇩🇲', iso: 'DM' },
  { code: '+593', name: 'Ecuador', flag: '🇪🇨', iso: 'EC' },
  { code: '+20', name: 'Egitto', flag: '🇪🇬', iso: 'EG' },
  { code: '+503', name: 'El Salvador', flag: '🇸🇻', iso: 'SV' },
  { code: '+971', name: 'Emirati Arabi Uniti', flag: '🇦🇪', iso: 'AE' },
  { code: '+291', name: 'Eritrea', flag: '🇪🇷', iso: 'ER' },
  { code: '+372', name: 'Estonia', flag: '🇪🇪', iso: 'EE' },
  { code: '+268', name: 'Eswatini', flag: '🇸🇿', iso: 'SZ' },
  { code: '+251', name: 'Etiopia', flag: '🇪🇹', iso: 'ET' },
  { code: '+679', name: 'Figi', flag: '🇫🇯', iso: 'FJ' },
  { code: '+63', name: 'Filippine', flag: '🇵🇭', iso: 'PH' },
  { code: '+358', name: 'Finlandia', flag: '🇫🇮', iso: 'FI' },
  { code: '+33', name: 'Francia', flag: '🇫🇷', iso: 'FR' },
  { code: '+241', name: 'Gabon', flag: '🇬🇦', iso: 'GA' },
  { code: '+220', name: 'Gambia', flag: '🇬🇲', iso: 'GM' },
  { code: '+995', name: 'Georgia', flag: '🇬🇪', iso: 'GE' },
  { code: '+49', name: 'Germania', flag: '🇩🇪', iso: 'DE' },
  { code: '+233', name: 'Ghana', flag: '🇬🇭', iso: 'GH' },
  { code: '+1876', name: 'Giamaica', flag: '🇯🇲', iso: 'JM' },
  { code: '+81', name: 'Giappone', flag: '🇯🇵', iso: 'JP' },
  { code: '+253', name: 'Gibuti', flag: '🇩🇯', iso: 'DJ' },
  { code: '+962', name: 'Giordania', flag: '🇯🇴', iso: 'JO' },
  { code: '+30', name: 'Grecia', flag: '🇬🇷', iso: 'GR' },
  { code: '+1473', name: 'Grenada', flag: '🇬🇩', iso: 'GD' },
  { code: '+502', name: 'Guatemala', flag: '🇬🇹', iso: 'GT' },
  { code: '+224', name: 'Guinea', flag: '🇬🇳', iso: 'GN' },
  { code: '+245', name: 'Guinea-Bissau', flag: '🇬🇼', iso: 'GW' },
  { code: '+240', name: 'Guinea Equatoriale', flag: '🇬🇶', iso: 'GQ' },
  { code: '+592', name: 'Guyana', flag: '🇬🇾', iso: 'GY' },
  { code: '+509', name: 'Haiti', flag: '🇭🇹', iso: 'HT' },
  { code: '+504', name: 'Honduras', flag: '🇭🇳', iso: 'HN' },
  { code: '+91', name: 'India', flag: '🇮🇳', iso: 'IN' },
  { code: '+62', name: 'Indonesia', flag: '🇮🇩', iso: 'ID' },
  { code: '+98', name: 'Iran', flag: '🇮🇷', iso: 'IR' },
  { code: '+964', name: 'Iraq', flag: '🇮🇶', iso: 'IQ' },
  { code: '+353', name: 'Irlanda', flag: '🇮🇪', iso: 'IE' },
  { code: '+354', name: 'Islanda', flag: '🇮🇸', iso: 'IS' },
  { code: '+972', name: 'Israele', flag: '🇮🇱', iso: 'IL' },
  { code: '+7', name: 'Kazakistan', flag: '🇰🇿', iso: 'KZ' },
  { code: '+254', name: 'Kenya', flag: '🇰🇪', iso: 'KE' },
  { code: '+996', name: 'Kirghizistan', flag: '🇰🇬', iso: 'KG' },
  { code: '+686', name: 'Kiribati', flag: '🇰🇮', iso: 'KI' },
  { code: '+965', name: 'Kuwait', flag: '🇰🇼', iso: 'KW' },
  { code: '+856', name: 'Laos', flag: '🇱🇦', iso: 'LA' },
  { code: '+266', name: 'Lesotho', flag: '🇱🇸', iso: 'LS' },
  { code: '+371', name: 'Lettonia', flag: '🇱🇻', iso: 'LV' },
  { code: '+961', name: 'Libano', flag: '🇱🇧', iso: 'LB' },
  { code: '+231', name: 'Liberia', flag: '🇱🇷', iso: 'LR' },
  { code: '+218', name: 'Libia', flag: '🇱🇾', iso: 'LY' },
  { code: '+423', name: 'Liechtenstein', flag: '🇱🇮', iso: 'LI' },
  { code: '+370', name: 'Lituania', flag: '🇱🇹', iso: 'LT' },
  { code: '+352', name: 'Lussemburgo', flag: '🇱🇺', iso: 'LU' },
  { code: '+389', name: 'Macedonia del Nord', flag: '🇲🇰', iso: 'MK' },
  { code: '+261', name: 'Madagascar', flag: '🇲🇬', iso: 'MG' },
  { code: '+265', name: 'Malawi', flag: '🇲🇼', iso: 'MW' },
  { code: '+60', name: 'Malesia', flag: '🇲🇾', iso: 'MY' },
  { code: '+960', name: 'Maldive', flag: '🇲🇻', iso: 'MV' },
  { code: '+223', name: 'Mali', flag: '🇲🇱', iso: 'ML' },
  { code: '+356', name: 'Malta', flag: '🇲🇹', iso: 'MT' },
  { code: '+212', name: 'Marocco', flag: '🇲🇦', iso: 'MA' },
  { code: '+230', name: 'Mauritius', flag: '🇲🇺', iso: 'MU' },
  { code: '+222', name: 'Mauritania', flag: '🇲🇷', iso: 'MR' },
  { code: '+52', name: 'Messico', flag: '🇲🇽', iso: 'MX' },
  { code: '+373', name: 'Moldavia', flag: '🇲🇩', iso: 'MD' },
  { code: '+377', name: 'Monaco', flag: '🇲🇨', iso: 'MC' },
  { code: '+976', name: 'Mongolia', flag: '🇲🇳', iso: 'MN' },
  { code: '+382', name: 'Montenegro', flag: '🇲🇪', iso: 'ME' },
  { code: '+258', name: 'Mozambico', flag: '🇲🇿', iso: 'MZ' },
  { code: '+264', name: 'Namibia', flag: '🇳🇦', iso: 'NA' },
  { code: '+674', name: 'Nauru', flag: '🇳🇷', iso: 'NR' },
  { code: '+977', name: 'Nepal', flag: '🇳🇵', iso: 'NP' },
  { code: '+505', name: 'Nicaragua', flag: '🇳🇮', iso: 'NI' },
  { code: '+227', name: 'Niger', flag: '🇳🇪', iso: 'NE' },
  { code: '+234', name: 'Nigeria', flag: '🇳🇬', iso: 'NG' },
  { code: '+47', name: 'Norvegia', flag: '🇳🇴', iso: 'NO' },
  { code: '+64', name: 'Nuova Zelanda', flag: '🇳🇿', iso: 'NZ' },
  { code: '+968', name: 'Oman', flag: '🇴🇲', iso: 'OM' },
  { code: '+31', name: 'Paesi Bassi', flag: '🇳🇱', iso: 'NL' },
  { code: '+92', name: 'Pakistan', flag: '🇵🇰', iso: 'PK' },
  { code: '+680', name: 'Palau', flag: '🇵🇼', iso: 'PW' },
  { code: '+970', name: 'Palestina', flag: '🇵🇸', iso: 'PS' },
  { code: '+507', name: 'Panama', flag: '🇵🇦', iso: 'PA' },
  { code: '+675', name: 'Papua Nuova Guinea', flag: '🇵🇬', iso: 'PG' },
  { code: '+595', name: 'Paraguay', flag: '🇵🇾', iso: 'PY' },
  { code: '+51', name: 'Perù', flag: '🇵🇪', iso: 'PE' },
  { code: '+48', name: 'Polonia', flag: '🇵🇱', iso: 'PL' },
  { code: '+351', name: 'Portogallo', flag: '🇵🇹', iso: 'PT' },
  { code: '+974', name: 'Qatar', flag: '🇶🇦', iso: 'QA' },
  { code: '+44', name: 'Regno Unito', flag: '🇬🇧', iso: 'GB' },
  { code: '+236', name: 'Repubblica Centrafricana', flag: '🇨🇫', iso: 'CF' },
  { code: '+420', name: 'Repubblica Ceca', flag: '🇨🇿', iso: 'CZ' },
  { code: '+1809', name: 'Repubblica Dominicana', flag: '🇩🇴', iso: 'DO' },
  { code: '+40', name: 'Romania', flag: '🇷🇴', iso: 'RO' },
  { code: '+250', name: 'Ruanda', flag: '🇷🇼', iso: 'RW' },
  { code: '+7', name: 'Russia', flag: '🇷🇺', iso: 'RU' },
  { code: '+1869', name: 'Saint Kitts e Nevis', flag: '🇰🇳', iso: 'KN' },
  { code: '+1758', name: 'Saint Lucia', flag: '🇱🇨', iso: 'LC' },
  { code: '+1784', name: 'Saint Vincent e Grenadine', flag: '🇻🇨', iso: 'VC' },
  { code: '+685', name: 'Samoa', flag: '🇼🇸', iso: 'WS' },
  { code: '+378', name: 'San Marino', flag: '🇸🇲', iso: 'SM' },
  { code: '+239', name: 'São Tomé e Príncipe', flag: '🇸🇹', iso: 'ST' },
  { code: '+221', name: 'Senegal', flag: '🇸🇳', iso: 'SN' },
  { code: '+381', name: 'Serbia', flag: '🇷🇸', iso: 'RS' },
  { code: '+248', name: 'Seychelles', flag: '🇸🇨', iso: 'SC' },
  { code: '+232', name: 'Sierra Leone', flag: '🇸🇱', iso: 'SL' },
  { code: '+65', name: 'Singapore', flag: '🇸🇬', iso: 'SG' },
  { code: '+963', name: 'Siria', flag: '🇸🇾', iso: 'SY' },
  { code: '+421', name: 'Slovacchia', flag: '🇸🇰', iso: 'SK' },
  { code: '+386', name: 'Slovenia', flag: '🇸🇮', iso: 'SI' },
  { code: '+252', name: 'Somalia', flag: '🇸🇴', iso: 'SO' },
  { code: '+34', name: 'Spagna', flag: '🇪🇸', iso: 'ES' },
  { code: '+94', name: 'Sri Lanka', flag: '🇱🇰', iso: 'LK' },
  { code: '+1', name: 'Stati Uniti', flag: '🇺🇸', iso: 'US' },
  { code: '+27', name: 'Sudafrica', flag: '🇿🇦', iso: 'ZA' },
  { code: '+249', name: 'Sudan', flag: '🇸🇩', iso: 'SD' },
  { code: '+211', name: 'Sudan del Sud', flag: '🇸🇸', iso: 'SS' },
  { code: '+597', name: 'Suriname', flag: '🇸🇷', iso: 'SR' },
  { code: '+46', name: 'Svezia', flag: '🇸🇪', iso: 'SE' },
  { code: '+41', name: 'Svizzera', flag: '🇨🇭', iso: 'CH' },
  { code: '+992', name: 'Tagikistan', flag: '🇹🇯', iso: 'TJ' },
  { code: '+255', name: 'Tanzania', flag: '🇹🇿', iso: 'TZ' },
  { code: '+66', name: 'Thailandia', flag: '🇹🇭', iso: 'TH' },
  { code: '+228', name: 'Togo', flag: '🇹🇬', iso: 'TG' },
  { code: '+676', name: 'Tonga', flag: '🇹🇴', iso: 'TO' },
  { code: '+1868', name: 'Trinidad e Tobago', flag: '🇹🇹', iso: 'TT' },
  { code: '+216', name: 'Tunisia', flag: '🇹🇳', iso: 'TN' },
  { code: '+90', name: 'Turchia', flag: '🇹🇷', iso: 'TR' },
  { code: '+993', name: 'Turkmenistan', flag: '🇹🇲', iso: 'TM' },
  { code: '+688', name: 'Tuvalu', flag: '🇹🇻', iso: 'TV' },
  { code: '+380', name: 'Ucraina', flag: '🇺🇦', iso: 'UA' },
  { code: '+256', name: 'Uganda', flag: '🇺🇬', iso: 'UG' },
  { code: '+36', name: 'Ungheria', flag: '🇭🇺', iso: 'HU' },
  { code: '+598', name: 'Uruguay', flag: '🇺🇾', iso: 'UY' },
  { code: '+998', name: 'Uzbekistan', flag: '🇺🇿', iso: 'UZ' },
  { code: '+678', name: 'Vanuatu', flag: '🇻🇺', iso: 'VU' },
  { code: '+379', name: 'Città del Vaticano', flag: '🇻🇦', iso: 'VA' },
  { code: '+58', name: 'Venezuela', flag: '🇻🇪', iso: 'VE' },
  { code: '+84', name: 'Vietnam', flag: '🇻🇳', iso: 'VN' },
  { code: '+967', name: 'Yemen', flag: '🇾🇪', iso: 'YE' },
  { code: '+260', name: 'Zambia', flag: '🇿🇲', iso: 'ZM' },
  { code: '+263', name: 'Zimbabwe', flag: '🇿🇼', iso: 'ZW' },
];

/**
 * Find a country entry by its dial code. Returns the first match (Italy is pinned first for +39).
 */
export function findCountryByCode(code: string): CountryDialCode | undefined {
  return COUNTRY_DIAL_CODES.find(c => c.code === code);
}
